config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :reviews, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :destroy, :update]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- [...] -->
</head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>

app/views/restaurants/edit.html.erb
<div class = "container">
<h1>Edit Restaurant</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
    <h1>All restaurants</h1>
  <ul>
    <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant_path(restaurant) do %>
      <%=  restaurant.name %>
      <% end %>
<!--       <%= restaurant.category %> -->
      <% end %>
    </li>
  </ul>
  <div>
    <%= link_to "Add Restaurant", new_restaurant_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1>Restaurant Show</h1>
  <h2> <%= @restaurant.name %> </h2>
  <h3> <%= @restaurant.address %> </h3>
  <h3> <%= @restaurant.phone_number %> </h3>
  <h3> <%= @restaurant.category %> </h3>

  <%= link_to "Update this restaurant", edit_restaurant_path, class: "btn btn-primary" %>
  <%= link_to "Delete this restaurant", restaurant_path, method: :delete, class: "btn btn-danger"  %>
  <%= link_to "View all restaurants", restaurants_path, class: "btn btn-info"  %>
  <%= link_to "Review this restaurant", new_restaurant_review_path(@restaurant), class: "btn btn-success"  %>

  <p>
    <strong>Reviews:</strong>
    <% @restaurant.reviews.each do |review| %>
      <li><%= link_to review.content, review_path(review) %></li>
    <% end %>
  </p>
  </div>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<%= link_to "Back to the restaurant", restaurant_path, class: "btn btn-info" %>

app/views/reviews/new.html.erb
<h1>Add a Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/reviews/show.html.erb
<h1>Review</h1>
<%= @review.content %>
<%= @review.rating %>
<%= link_to "Back to the restaurant", restaurant_path, class: "btn btn-info" %>